management:
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
  metrics:
    tags:
      application: Bell  # добавляет тег ко всем метрикам

server:
  port: 12222  # Порт приложения
  shutdown: graceful
  connection-timeout: 2m

spring:
  application:
    name: Bell  # Имя приложения
  jmx:
    enabled: true  # Включение JMX
  kafka:
    bootstrap-servers: localhost:9092  # Адрес Kafka
    producer:
#      acks: all  # Гарантия доставки сообщений
#      retries: 3  # Количество повторных попыток
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # JSON сериализатор
      properties:
        enable.idempotence: true  # Идемпотентность продюсера
    consumer:
      group-id: my-group  # ID группы потребителей
      auto-offset-reset: earliest  # Чтение с начала топика
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  webflux:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: postgres
    password: example
    pool:
      enabled: true
      max-size: 20

#  datasource:
#    url: jdbc:postgresql://localhost:5432/mydb  # URL PostgreSQL
#    username: postgres
#    password: example
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 50  # Максимальный размер пула соединений
#      minimum-idle: 10  # Минимальное количество idle соединений
#      connection-timeout: 5000  # Таймаут соединения (10 сек)
#      idle-timeout: 300000  # Таймаут idle соединения (5 мин)
#      max-lifetime: 1800000  # Максимальное время жизни соединения (30 мин)

  jpa:
    hibernate:
      ddl-auto: create-drop  # Автоматическое создание/удаление таблиц
    properties:
      hibernate:
        jdbc:
          batch_size: 50  # Размер батча для bulk операций
          fetch_size: 100
        query:
          in_clause_parameter_padding: true
    show-sql: false  # Отключение логирования SQL
    open-in-view: false

# Конфигурация задержек для эндпоинтов
response:
  delay:
    delays:
      session.create: 500  # 500 мс задержка для создания сессии
      session.delete: 500  # 500 мс задержка для удаления сессии
      session.check: 0  # Без задержки для проверки сессии
      order.create: 3000  # 3 сек задержка для создания заказа
      order.getProducts: 1500  # 1.5 сек задержка для получения продуктов
      order.getOrder: 1500  # 1.5 сек задержка для получения заказа

logging:
  level:
    root: INFO
    BellSpring: INFO


#  ERROR (самый важный) ⬇
#  WARN  ⬇
#  INFO  ⬇
#  DEBUG ⬇
#  TRACE (самый подробный)

