management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus

server:
  port: 12222
  tomcat:
    threads:
      max: 5000
      min-spare: 20
    accept-count: 100
    max-connections: 20000
    mbeanregistry:
      enabled: true

spring:
  application:
    name: Bell
  jmx:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      group-id: my-group               # ID группы потребителей
      auto-offset-reset: earliest      # Чтение сообщений с начала топика
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer    # Десериализатор ключей
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Десериализатор значений

  datasource:
    # Настройки подключения к PostgreSQL
    url: jdbc:postgresql://localhost:5432/mydb  # URL базы данных
    username: postgres                          # Имя пользователя БД
    password: example                           # Пароль пользователя БД
    driver-class-name: org.postgresql.Driver    # Драйвер PostgreSQL

  jpa:
    # Настройки JPA и Hibernate
    hibernate:
      ddl-auto: create-drop  # Автоматическое создание/удаление таблиц при запуске/остановке
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект PostgreSQL для Hibernate
    show-sql: true

response:
  delay:
    default: 0
    session:
      create: 500
      delete: 500
      check: 0
    order:
      create: 3000
      getProducts: 1500
      getOrder: 1500





